name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]
        platform:
        - os: ubuntu-latest
          shell: bash
        - os: macos-latest
          shell: bash
        - os: windows-latest
          shell: bash
        - os: windows-latest
          shell: powershell
        exclude:
        # Presumably these worked at some point in the past, but now actions/setup-node gives errors like
        #   Unable to find Node version '14.x' for platform darwin and architecture arm64.
        - node-version: 12.x
          platform:
            os: macos-latest
            shell: bash
        - node-version: 14.x
          platform:
            os: macos-latest
            shell: bash
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- -c -t0
